-- Load pgTAP for unit testing
CREATE EXTENSION IF NOT EXISTS pgtap;

-- Start a transaction to ensure changes are rolled back
BEGIN;

-- Plan to run 1 test
SELECT plan(1);  

-- ✅ Test 1: Insert a User into auth.users
INSERT INTO auth.users (id, email)
VALUES (gen_random_uuid(), 'testuser@example.com');

-- Check that the profile was autogenerated in public.profiles by the trigger on auth.users
SELECT results_eq(
    'SELECT COUNT(*)::integer FROM auth.users WHERE email = ''testuser@example.com''',
    ARRAY[1],
    'Profile should be autogenerated successfully.'
);

-- Finish the test
SELECT * FROM finish();

-- Rollback the transaction to undo all changes made during the test
ROLLBACK;