INSERT INTO public.teams
    (league_id, team_sport, team_location, team_abbreviation, team_nickname)
VALUES
    -- NBA Teams
    (1, 'Basketball', 'Boston', 'BOS', 'Celtics'),
    (1, 'Basketball', 'Brooklyn', 'BKN', 'Nets'),
    (1, 'Basketball', 'New York', 'NYK', 'Knicks'),
    (1, 'Basketball', 'Philadelphia', 'PHI', '76ers'),
    (1, 'Basketball', 'Toronto', 'TOR', 'Raptors'),
    (1, 'Basketball', 'Chicago', 'CHI', 'Bulls'),
    (1, 'Basketball', 'Cleveland', 'CLE', 'Cavaliers'),
    (1, 'Basketball', 'Detroit', 'DET', 'Pistons'),
    (1, 'Basketball', 'Indiana', 'IND', 'Pacers'),
    (1, 'Basketball', 'Milwaukee', 'MIL', 'Bucks'),
    (1, 'Basketball', 'Atlanta', 'ATL', 'Hawks'),
    (1, 'Basketball', 'Charlotte', 'CHA', 'Hornets'),
    (1, 'Basketball', 'Miami', 'MIA', 'Heat'),
    (1, 'Basketball', 'Orlando', 'ORL', 'Magic'),
    (1, 'Basketball', 'Washington', 'WAS', 'Wizards'),
    (1, 'Basketball', 'Denver', 'DEN', 'Nuggets'),
    (1, 'Basketball', 'Minnesota', 'MIN', 'Timberwolves'),
    (1, 'Basketball', 'Oklahoma City', 'OKC', 'Thunder'),
    (1, 'Basketball', 'Portland', 'POR', 'Trail Blazers'),
    (1, 'Basketball', 'Utah', 'UTA', 'Jazz'),
    (1, 'Basketball', 'Golden State', 'GSW', 'Warriors'),
    (1, 'Basketball', 'Los Angeles', 'LAC', 'Clippers'),
    (1, 'Basketball', 'Los Angeles', 'LAL', 'Lakers'),
    (1, 'Basketball', 'Phoenix', 'PHX', 'Suns'),
    (1, 'Basketball', 'Sacramento', 'SAC', 'Kings'),
    (1, 'Basketball', 'Dallas', 'DAL', 'Mavericks'),
    (1, 'Basketball', 'Houston', 'HOU', 'Rockets'),
    (1, 'Basketball', 'Memphis', 'MEM', 'Grizzlies'),
    (1, 'Basketball', 'New Orleans', 'NOP', 'Pelicans'),
    (1, 'Basketball', 'San Antonio', 'SAS', 'Spurs'),

    -- NFL Teams
    (2, 'Football', 'Arizona', 'ARI', 'Cardinals'),
    (2, 'Football', 'Atlanta', 'ATL', 'Falcons'),
    (2, 'Football', 'Baltimore', 'BAL', 'Ravens'),
    (2, 'Football', 'Buffalo', 'BUF', 'Bills'),
    (2, 'Football', 'Carolina', 'CAR', 'Panthers'),
    (2, 'Football', 'Chicago', 'CHI', 'Bears'),
    (2, 'Football', 'Cincinnati', 'CIN', 'Bengals'),
    (2, 'Football', 'Cleveland', 'CLE', 'Browns'),
    (2, 'Football', 'Dallas', 'DAL', 'Cowboys'),
    (2, 'Football', 'Denver', 'DEN', 'Broncos'),
    (2, 'Football', 'Detroit', 'DET', 'Lions'),
    (2, 'Football', 'Green Bay', 'GB', 'Packers'),
    (2, 'Football', 'Houston', 'HOU', 'Texans'),
    (2, 'Football', 'Indianapolis', 'IND', 'Colts'),
    (2, 'Football', 'Jacksonville', 'JAX', 'Jaguars'),
    (2, 'Football', 'Kansas City', 'KC', 'Chiefs'),
    (2, 'Football', 'Las Vegas', 'LV', 'Raiders'),
    (2, 'Football', 'Los Angeles', 'LAC', 'Chargers'),
    (2, 'Football', 'Los Angeles', 'LAR', 'Rams'),
    (2, 'Football', 'Miami', 'MIA', 'Dolphins'),
    (2, 'Football', 'Minnesota', 'MIN', 'Vikings'),
    (2, 'Football', 'New England', 'NE', 'Patriots'),
    (2, 'Football', 'New Orleans', 'NO', 'Saints'),
    (2, 'Football', 'New York', 'NYG', 'Giants'),
    (2, 'Football', 'New York', 'NYJ', 'Jets'),
    (2, 'Football', 'Philadelphia', 'PHI', 'Eagles'),
    (2, 'Football', 'Pittsburgh', 'PIT', 'Steelers'),
    (2, 'Football', 'San Francisco', 'SF', '49ers'),
    (2, 'Football', 'Seattle', 'SEA', 'Seahawks'),
    (2, 'Football', 'Tampa Bay', 'TB', 'Buccaneers'),
    (2, 'Football', 'Tennessee', 'TEN', 'Titans'),
    (2, 'Football', 'Washington', 'WAS', 'Commanders'),

    -- MLB Teams
    (3, 'Baseball', 'Boston', 'BOS', 'Red Sox'),
    (3, 'Baseball', 'New York', 'NYY', 'Yankees'),
    (3, 'Baseball', 'Los Angeles', 'LAD', 'Dodgers'),
    (3, 'Baseball', 'Baltimore', 'BAL', 'Orioles'),
    (3, 'Baseball', 'Toronto', 'TOR', 'Blue Jays'),
    (3, 'Baseball', 'Tampa Bay', 'TB', 'Rays'),
    (3, 'Baseball', 'Chicago', 'CHW', 'White Sox'),
    (3, 'Baseball', 'Cleveland', 'CLE', 'Guardians'),
    (3, 'Baseball', 'Detroit', 'DET', 'Tigers'),
    (3, 'Baseball', 'Minnesota', 'MIN', 'Twins'),
    (3, 'Baseball', 'Houston', 'HOU', 'Astros'),
    (3, 'Baseball', 'Seattle', 'SEA', 'Mariners'),
    (3, 'Baseball', 'Texas', 'TEX', 'Rangers'),
    (3, 'Baseball', 'Oakland', 'OAK', 'Athletics'),
    (3, 'Baseball', 'Atlanta', 'ATL', 'Braves'),
    (3, 'Baseball', 'Philadelphia', 'PHI', 'Phillies'),
    (3, 'Baseball', 'Washington', 'WSH', 'Nationals'),
    (3, 'Baseball', 'Miami', 'MIA', 'Marlins'),
    (3, 'Baseball', 'Milwaukee', 'MIL', 'Brewers'),
    (3, 'Baseball', 'St. Louis', 'STL', 'Cardinals'),
    (3, 'Baseball', 'Chicago', 'CHC', 'Cubs'),
    (3, 'Baseball', 'Cincinnati', 'CIN', 'Reds'),
    (3, 'Baseball', 'Pittsburgh', 'PIT', 'Pirates'),
    (3, 'Baseball', 'Arizona', 'ARI', 'Diamondbacks'),
    (3, 'Baseball', 'San Diego', 'SD', 'Padres'),
    (3, 'Baseball', 'San Francisco', 'SF', 'Giants'),
    (3, 'Baseball', 'Colorado', 'COL', 'Rockies'),
    (3, 'Baseball', 'New York', 'NYM', 'Mets');
