INSERT INTO public.teams
    (league_id, team_sport, team_location, team_abbreviation, team_nickname, team_primary_hex_color, team_secondary_hex_color)
VALUES
    -- NBA Teams
    (2, 'Basketball', 'Boston', 'BOS', 'Celtics', NULL, NULL),
    (2, 'Basketball', 'Brooklyn', 'BKN', 'Nets', NULL, NULL),
    (2, 'Basketball', 'New York', 'NYK', 'Knicks', NULL, NULL),
    (2, 'Basketball', 'Philadelphia', 'PHI', '76ers', NULL, NULL),
    (2, 'Basketball', 'Toronto', 'TOR', 'Raptors', NULL, NULL),
    (2, 'Basketball', 'Chicago', 'CHI', 'Bulls', NULL, NULL),
    (2, 'Basketball', 'Cleveland', 'CLE', 'Cavaliers', NULL, NULL),
    (2, 'Basketball', 'Detroit', 'DET', 'Pistons', NULL, NULL),
    (2, 'Basketball', 'Indiana', 'IND', 'Pacers', NULL, NULL),
    (2, 'Basketball', 'Milwaukee', 'MIL', 'Bucks', NULL, NULL),
    (2, 'Basketball', 'Atlanta', 'ATL', 'Hawks', NULL, NULL),
    (2, 'Basketball', 'Charlotte', 'CHA', 'Hornets', NULL, NULL),
    (2, 'Basketball', 'Miami', 'MIA', 'Heat', NULL, NULL),
    (2, 'Basketball', 'Orlando', 'ORL', 'Magic', NULL, NULL),
    (2, 'Basketball', 'Washington', 'WAS', 'Wizards', NULL, NULL),
    (2, 'Basketball', 'Denver', 'DEN', 'Nuggets', NULL, NULL),
    (2, 'Basketball', 'Minnesota', 'MIN', 'Timberwolves', NULL, NULL),
    (2, 'Basketball', 'Oklahoma City', 'OKC', 'Thunder', NULL, NULL),
    (2, 'Basketball', 'Portland', 'POR', 'Trail Blazers', NULL, NULL),
    (2, 'Basketball', 'Utah', 'UTA', 'Jazz', NULL, NULL),
    (2, 'Basketball', 'Golden State', 'GSW', 'Warriors', NULL, NULL),
    (2, 'Basketball', 'Los Angeles', 'LAC', 'Clippers', NULL, NULL),
    (2, 'Basketball', 'Los Angeles', 'LAL', 'Lakers', NULL, NULL),
    (2, 'Basketball', 'Phoenix', 'PHX', 'Suns', NULL, NULL),
    (2, 'Basketball', 'Sacramento', 'SAC', 'Kings', NULL, NULL),
    (2, 'Basketball', 'Dallas', 'DAL', 'Mavericks', NULL, NULL),
    (2, 'Basketball', 'Houston', 'HOU', 'Rockets', NULL, NULL),
    (2, 'Basketball', 'Memphis', 'MEM', 'Grizzlies', NULL, NULL),
    (2, 'Basketball', 'New Orleans', 'NOP', 'Pelicans', NULL, NULL),
    (2, 'Basketball', 'San Antonio', 'SAS', 'Spurs', NULL, NULL),

    -- NFL Teams
    (3, 'Football', 'Arizona', 'ARI', 'Cardinals', NULL, NULL),
    (3, 'Football', 'Atlanta', 'ATL', 'Falcons', NULL, NULL),
    (3, 'Football', 'Baltimore', 'BAL', 'Ravens', NULL, NULL),
    (3, 'Football', 'Buffalo', 'BUF', 'Bills', NULL, NULL),
    (3, 'Football', 'Carolina', 'CAR', 'Panthers', NULL, NULL),
    (3, 'Football', 'Chicago', 'CHI', 'Bears', NULL, NULL),
    (3, 'Football', 'Cincinnati', 'CIN', 'Bengals', NULL, NULL),
    (3, 'Football', 'Cleveland', 'CLE', 'Browns', NULL, NULL),
    (3, 'Football', 'Dallas', 'DAL', 'Cowboys', NULL, NULL),
    (3, 'Football', 'Denver', 'DEN', 'Broncos', NULL, NULL),
    (3, 'Football', 'Detroit', 'DET', 'Lions', NULL, NULL),
    (3, 'Football', 'Green Bay', 'GB', 'Packers', NULL, NULL),
    (3, 'Football', 'Houston', 'HOU', 'Texans', NULL, NULL),
    (3, 'Football', 'Indianapolis', 'IND', 'Colts', NULL, NULL),
    (3, 'Football', 'Jacksonville', 'JAX', 'Jaguars', NULL, NULL),
    (3, 'Football', 'Kansas City', 'KC', 'Chiefs', NULL, NULL),
    (3, 'Football', 'Las Vegas', 'LV', 'Raiders', NULL, NULL),
    (3, 'Football', 'Los Angeles', 'LAC', 'Chargers', NULL, NULL),
    (3, 'Football', 'Los Angeles', 'LAR', 'Rams', NULL, NULL),
    (3, 'Football', 'Miami', 'MIA', 'Dolphins', NULL, NULL),
    (3, 'Football', 'Minnesota', 'MIN', 'Vikings', NULL, NULL),
    (3, 'Football', 'New England', 'NE', 'Patriots', NULL, NULL),
    (3, 'Football', 'New Orleans', 'NO', 'Saints', NULL, NULL),
    (3, 'Football', 'New York', 'NYG', 'Giants', NULL, NULL),
    (3, 'Football', 'New York', 'NYJ', 'Jets', NULL, NULL),
    (3, 'Football', 'Philadelphia', 'PHI', 'Eagles', NULL, NULL),
    (3, 'Football', 'Pittsburgh', 'PIT', 'Steelers', NULL, NULL),
    (3, 'Football', 'San Francisco', 'SF', '49ers', NULL, NULL),
    (3, 'Football', 'Seattle', 'SEA', 'Seahawks', NULL, NULL),
    (3, 'Football', 'Tampa Bay', 'TB', 'Buccaneers', NULL, NULL),
    (3, 'Football', 'Tennessee', 'TEN', 'Titans', NULL, NULL),
    (3, 'Football', 'Washington', 'WAS', 'Commanders', NULL, NULL),

    -- MLB Teams
    (1, 'Baseball', 'Boston', 'BOS', 'Red Sox', 'BD3039', '0C2340'),
    (1, 'Baseball', 'New York', 'NYY', 'Yankees', '003087', 'E4002C'),
    (1, 'Baseball', 'Los Angeles', 'LAD', 'Dodgers', '005A9C', 'EF3E42'),
    (1, 'Baseball', 'Los Angeles', 'LAA', 'Angels', '003263', 'BA0021'),
    (1, 'Baseball', 'Baltimore', 'BAL', 'Orioles', 'DF4601', '000000'),
    (1, 'Baseball', 'Toronto', 'TOR', 'Blue Jays', '134A8E', '1D2D5C'),
    (1, 'Baseball', 'Tampa Bay', 'TB', 'Rays', '092C5C', '8FBCE6'),
    (1, 'Baseball', 'Chicago', 'CHW', 'White Sox', '27251F', 'C4CED4'),
    (1, 'Baseball', 'Cleveland', 'CLE', 'Guardians', '00385D', 'E50022'),
    (1, 'Baseball', 'Detroit', 'DET', 'Tigers', '0C2340', 'FA4616'),
    (1, 'Baseball', 'Kansas City', 'KC', 'Royals', '004687', 'BD9B60'),
    (1, 'Baseball', 'Minnesota', 'MIN', 'Twins', '002B5C', 'D31145'),
    (1, 'Baseball', 'Houston', 'HOU', 'Astros', '002D62', 'EB6E1F'),
    (1, 'Baseball', 'Seattle', 'SEA', 'Mariners', '0C2C56', '005C5C'),
    (1, 'Baseball', 'Texas', 'TEX', 'Rangers', '003278', 'C0111F'),
    (1, 'Baseball', 'Las Vegas', 'ATH', 'Athletics', '003831', 'EFB21E'),
    (1, 'Baseball', 'Atlanta', 'ATL', 'Braves', 'CE1141', '13274F'),
    (1, 'Baseball', 'Philadelphia', 'PHI', 'Phillies', 'E81828', '002D72'),
    (1, 'Baseball', 'Washington', 'WSH', 'Nationals', 'AB0003', '14225A'),
    (1, 'Baseball', 'Miami', 'MIA', 'Marlins', '00A3E0', 'EF3340'),
    (1, 'Baseball', 'Milwaukee', 'MIL', 'Brewers', '12284B', 'FFC52F'),
    (1, 'Baseball', 'St. Louis', 'STL', 'Cardinals', 'C41E3A', '0C2340'),
    (1, 'Baseball', 'Chicago', 'CHC', 'Cubs', '0E3386', 'CC3433'),
    (1, 'Baseball', 'Cincinnati', 'CIN', 'Reds', 'C6011F', '000000'),
    (1, 'Baseball', 'Pittsburgh', 'PIT', 'Pirates', '27251F', 'FDB827'),
    (1, 'Baseball', 'Arizona', 'ARI', 'Diamondbacks', 'A71930', 'E3D4AD'),
    (1, 'Baseball', 'San Diego', 'SD', 'Padres', '2F241D', 'FFC425'),
    (1, 'Baseball', 'San Francisco', 'SF', 'Giants', 'FD5A1E', '27251F'),
    (1, 'Baseball', 'Colorado', 'COL', 'Rockies', '333366', 'C4CED4'),
    (1, 'Baseball', 'New York', 'NYM', 'Mets', '002D72', 'FF5910');
