INSERT INTO public.teams
    (league_id, team_sport, team_location, team_abbreviation, team_nickname, team_primary_hex_color, team_secondary_hex_color, team_api_id)
VALUES
    -- NBA Teams
    (2, 'Basketball', 'Boston', 'BOS', 'Celtics', NULL, NULL, 133),
    (2, 'Basketball', 'Brooklyn', 'BKN', 'Nets', NULL, NULL, 134),
    (2, 'Basketball', 'New York', 'NYK', 'Knicks', NULL, NULL, 151),
    (2, 'Basketball', 'Philadelphia', 'PHI', '76ers', NULL, NULL, 154),
    (2, 'Basketball', 'Toronto', 'TOR', 'Raptors', NULL, NULL, 159),
    (2, 'Basketball', 'Chicago', 'CHI', 'Bulls', NULL, NULL, 136),
    (2, 'Basketball', 'Cleveland', 'CLE', 'Cavaliers', NULL, NULL, 137),
    (2, 'Basketball', 'Detroit', 'DET', 'Pistons', NULL, NULL, 140),
    (2, 'Basketball', 'Indiana', 'IND', 'Pacers', NULL, NULL, 143),
    (2, 'Basketball', 'Milwaukee', 'MIL', 'Bucks', NULL, NULL, 148),
    (2, 'Basketball', 'Atlanta', 'ATL', 'Hawks', NULL, NULL, 132),
    (2, 'Basketball', 'Charlotte', 'CHA', 'Hornets', NULL, NULL, 135),
    (2, 'Basketball', 'Miami', 'MIA', 'Heat', NULL, NULL, 147),
    (2, 'Basketball', 'Orlando', 'ORL', 'Magic', NULL, NULL, 153),
    (2, 'Basketball', 'Washington', 'WAS', 'Wizards', NULL, NULL, 161),
    (2, 'Basketball', 'Denver', 'DEN', 'Nuggets', NULL, NULL, 139),
    (2, 'Basketball', 'Minnesota', 'MIN', 'Timberwolves', NULL, NULL, 149),
    (2, 'Basketball', 'Oklahoma City', 'OKC', 'Thunder', NULL, NULL, 152),
    (2, 'Basketball', 'Portland', 'POR', 'Trail Blazers', NULL, NULL, 156),
    (2, 'Basketball', 'Utah', 'UTA', 'Jazz', NULL, NULL, 160),
    (2, 'Basketball', 'Golden State', 'GSW', 'Warriors', NULL, NULL, 141),
    (2, 'Basketball', 'Los Angeles', 'LAC', 'Clippers', NULL, NULL, 144),
    (2, 'Basketball', 'Los Angeles', 'LAL', 'Lakers', NULL, NULL, 145),
    (2, 'Basketball', 'Phoenix', 'PHX', 'Suns', NULL, NULL, 155),
    (2, 'Basketball', 'Sacramento', 'SAC', 'Kings', NULL, NULL, 157),
    (2, 'Basketball', 'Dallas', 'DAL', 'Mavericks', NULL, NULL, 138),
    (2, 'Basketball', 'Houston', 'HOU', 'Rockets', NULL, NULL, 142),
    (2, 'Basketball', 'Memphis', 'MEM', 'Grizzlies', NULL, NULL, 146),
    (2, 'Basketball', 'New Orleans', 'NOP', 'Pelicans', NULL, NULL, 150),
    (2, 'Basketball', 'San Antonio', 'SAS', 'Spurs', NULL, NULL, 158),

    -- NFL Teams
    (3, 'Football', 'Arizona', 'ARI', 'Cardinals', NULL, NULL, NULL),
    (3, 'Football', 'Atlanta', 'ATL', 'Falcons', NULL, NULL, NULL),
    (3, 'Football', 'Baltimore', 'BAL', 'Ravens', NULL, NULL, NULL),
    (3, 'Football', 'Buffalo', 'BUF', 'Bills', NULL, NULL, NULL),
    (3, 'Football', 'Carolina', 'CAR', 'Panthers', NULL, NULL, NULL),
    (3, 'Football', 'Chicago', 'CHI', 'Bears', NULL, NULL, NULL),
    (3, 'Football', 'Cincinnati', 'CIN', 'Bengals', NULL, NULL, NULL),
    (3, 'Football', 'Cleveland', 'CLE', 'Browns', NULL, NULL, NULL),
    (3, 'Football', 'Dallas', 'DAL', 'Cowboys', NULL, NULL, NULL),
    (3, 'Football', 'Denver', 'DEN', 'Broncos', NULL, NULL, NULL),
    (3, 'Football', 'Detroit', 'DET', 'Lions', NULL, NULL, NULL),
    (3, 'Football', 'Green Bay', 'GB', 'Packers', NULL, NULL, NULL),
    (3, 'Football', 'Houston', 'HOU', 'Texans', NULL, NULL, NULL),
    (3, 'Football', 'Indianapolis', 'IND', 'Colts', NULL, NULL, NULL),
    (3, 'Football', 'Jacksonville', 'JAX', 'Jaguars', NULL, NULL, NULL),
    (3, 'Football', 'Kansas City', 'KC', 'Chiefs', NULL, NULL, NULL),
    (3, 'Football', 'Las Vegas', 'LV', 'Raiders', NULL, NULL, NULL),
    (3, 'Football', 'Los Angeles', 'LAC', 'Chargers', NULL, NULL, NULL),
    (3, 'Football', 'Los Angeles', 'LAR', 'Rams', NULL, NULL, NULL),
    (3, 'Football', 'Miami', 'MIA', 'Dolphins', NULL, NULL, NULL),
    (3, 'Football', 'Minnesota', 'MIN', 'Vikings', NULL, NULL, NULL),
    (3, 'Football', 'New England', 'NE', 'Patriots', NULL, NULL, NULL),
    (3, 'Football', 'New Orleans', 'NO', 'Saints', NULL, NULL, NULL),
    (3, 'Football', 'New York', 'NYG', 'Giants', NULL, NULL, NULL),
    (3, 'Football', 'New York', 'NYJ', 'Jets', NULL, NULL, NULL),
    (3, 'Football', 'Philadelphia', 'PHI', 'Eagles', NULL, NULL, NULL),
    (3, 'Football', 'Pittsburgh', 'PIT', 'Steelers', NULL, NULL, NULL),
    (3, 'Football', 'San Francisco', 'SF', '49ers', NULL, NULL, NULL),
    (3, 'Football', 'Seattle', 'SEA', 'Seahawks', NULL, NULL, NULL),
    (3, 'Football', 'Tampa Bay', 'TB', 'Buccaneers', NULL, NULL, NULL),
    (3, 'Football', 'Tennessee', 'TEN', 'Titans', NULL, NULL, NULL),
    (3, 'Football', 'Washington', 'WAS', 'Commanders', NULL, NULL, NULL),

    -- MLB Teams
    (1, 'Baseball', 'Boston', 'BOS', 'Red Sox', '#BD3039', '#0C2340', NULL),
    (1, 'Baseball', 'New York', 'NYY', 'Yankees', '#003087', '#E4002C', NULL),
    (1, 'Baseball', 'Los Angeles', 'LAD', 'Dodgers', '#005A9C', '#EF3E42', NULL),
    (1, 'Baseball', 'Los Angeles', 'LAA', 'Angels', '#003263', '#BA0021', NULL),
    (1, 'Baseball', 'Baltimore', 'BAL', 'Orioles', '#DF4601', '#000000', NULL),
    (1, 'Baseball', 'Toronto', 'TOR', 'Blue Jays', '#134A8E', '#1D2D5C', NULL),
    (1, 'Baseball', 'Tampa Bay', 'TB', 'Rays', '#092C5C', '#8FBCE6', NULL),
    (1, 'Baseball', 'Chicago', 'CHW', 'White Sox', '#27251F', '#C4CED4', NULL),
    (1, 'Baseball', 'Cleveland', 'CLE', 'Guardians', '#00385D', '#E50022', NULL),
    (1, 'Baseball', 'Detroit', 'DET', 'Tigers', '#0C2340', '#FA4616', NULL),
    (1, 'Baseball', 'Kansas City', 'KC', 'Royals', '#004687', '#BD9B60', NULL),
    (1, 'Baseball', 'Minnesota', 'MIN', 'Twins', '#002B5C', '#D31145', NULL),
    (1, 'Baseball', 'Houston', 'HOU', 'Astros', '#002D62', '#EB6E1F', NULL),
    (1, 'Baseball', 'Seattle', 'SEA', 'Mariners', '#0C2C56', '#005C5C', NULL),
    (1, 'Baseball', 'Texas', 'TEX', 'Rangers', '#003278', '#C0111F', NULL),
    (1, 'Baseball', 'Las Vegas', 'ATH', 'Athletics', '#003831', '#EFB21E', NULL),
    (1, 'Baseball', 'Atlanta', 'ATL', 'Braves', '#CE1141', '#13274F', NULL),
    (1, 'Baseball', 'Philadelphia', 'PHI', 'Phillies', '#E81828', '#002D72', NULL),
    (1, 'Baseball', 'Washington', 'WSH', 'Nationals', '#AB0003', '#14225A', NULL),
    (1, 'Baseball', 'Miami', 'MIA', 'Marlins', '#00A3E0', '#EF3340', NULL),
    (1, 'Baseball', 'Milwaukee', 'MIL', 'Brewers', '#12284B', '#FFC52F', NULL),
    (1, 'Baseball', 'St. Louis', 'STL', 'Cardinals', '#C41E3A', '#0C2340', NULL),
    (1, 'Baseball', 'Chicago', 'CHC', 'Cubs', '#0E3386', '#CC3433', NULL),
    (1, 'Baseball', 'Cincinnati', 'CIN', 'Reds', '#C6011F', '#000000', NULL),
    (1, 'Baseball', 'Pittsburgh', 'PIT', 'Pirates', '#27251F', '#FDB827', NULL),
    (1, 'Baseball', 'Arizona', 'ARI', 'Diamondbacks', '#A71930', '#E3D4AD', NULL),
    (1, 'Baseball', 'San Diego', 'SD', 'Padres', '#2F241D', '#FFC425', NULL),
    (1, 'Baseball', 'San Francisco', 'SF', 'Giants', '#FD5A1E', '#27251F', NULL),
    (1, 'Baseball', 'Colorado', 'COL', 'Rockies', '#333366', '#C4CED4', NULL),
    (1, 'Baseball', 'New York', 'NYM', 'Mets', '#002D72', '#FF5910', NULL);
