const games = [{
  "league": "NBA",
  "data": {
    "get": "games",
    "parameters": {
      "date": "2025-03-04",
      "league": "12",
      "season": "2024-2025",
    },
    "errors": [],
    "results": 7,
    "response": [{
      "id": 414748,
      "date": "2025-03-04T00:00:00+00:00",
      "time": "00:00",
      "timestamp": 1741046400,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "Spectrum Center",
      "status": { "long": "Game Finished", "short": "FT", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 135,
          "name": "Charlotte Hornets",
          "logo": "https://media.api-sports.io/basketball/teams/135.png",
        },
        "away": {
          "id": 141,
          "name": "Golden State Warriors",
          "logo": "https://media.api-sports.io/basketball/teams/141.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": 21,
          "quarter_2": 28,
          "quarter_3": 28,
          "quarter_4": 24,
          "over_time": null,
          "total": 101,
        },
        "away": {
          "quarter_1": 28,
          "quarter_2": 30,
          "quarter_3": 28,
          "quarter_4": 33,
          "over_time": null,
          "total": 119,
        },
      },
    }, {
      "id": 414749,
      "date": "2025-03-04T00:00:00+00:00",
      "time": "00:00",
      "timestamp": 1741046400,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "Wells Fargo Center",
      "status": { "long": "Game Finished", "short": "FT", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 154,
          "name": "Philadelphia 76ers",
          "logo": "https://media.api-sports.io/basketball/teams/154.png",
        },
        "away": {
          "id": 156,
          "name": "Portland Trail Blazers",
          "logo": "https://media.api-sports.io/basketball/teams/156.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": 32,
          "quarter_2": 29,
          "quarter_3": 20,
          "quarter_4": 21,
          "over_time": null,
          "total": 102,
        },
        "away": {
          "quarter_1": 29,
          "quarter_2": 27,
          "quarter_3": 35,
          "quarter_4": 28,
          "over_time": null,
          "total": 119,
        },
      },
    }, {
      "id": 414750,
      "date": "2025-03-04T00:30:00+00:00",
      "time": "00:30",
      "timestamp": 1741048200,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "Kaseya Center",
      "status": { "long": "Game Finished", "short": "FT", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 147,
          "name": "Miami Heat",
          "logo": "https://media.api-sports.io/basketball/teams/147.png",
        },
        "away": {
          "id": 161,
          "name": "Washington Wizards",
          "logo": "https://media.api-sports.io/basketball/teams/161.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": 32,
          "quarter_2": 23,
          "quarter_3": 26,
          "quarter_4": 25,
          "over_time": null,
          "total": 106,
        },
        "away": {
          "quarter_1": 24,
          "quarter_2": 12,
          "quarter_3": 32,
          "quarter_4": 22,
          "over_time": null,
          "total": 90,
        },
      },
    }, {
      "id": 414751,
      "date": "2025-03-04T01:00:00+00:00",
      "time": "01:00",
      "timestamp": 1741050000,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "FedExForum",
      "status": { "long": "Game Finished", "short": "FT", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 146,
          "name": "Memphis Grizzlies",
          "logo": "https://media.api-sports.io/basketball/teams/146.png",
        },
        "away": {
          "id": 132,
          "name": "Atlanta Hawks",
          "logo": "https://media.api-sports.io/basketball/teams/132.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": 34,
          "quarter_2": 31,
          "quarter_3": 42,
          "quarter_4": 23,
          "over_time": null,
          "total": 130,
        },
        "away": {
          "quarter_1": 28,
          "quarter_2": 42,
          "quarter_3": 31,
          "quarter_4": 31,
          "over_time": null,
          "total": 132,
        },
      },
    }, {
      "id": 414752,
      "date": "2025-03-04T01:00:00+00:00",
      "time": "01:00",
      "timestamp": 1741050000,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "Paycom Center",
      "status": { "long": "Game Finished", "short": "FT", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 152,
          "name": "Oklahoma City Thunder",
          "logo": "https://media.api-sports.io/basketball/teams/152.png",
        },
        "away": {
          "id": 142,
          "name": "Houston Rockets",
          "logo": "https://media.api-sports.io/basketball/teams/142.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": 30,
          "quarter_2": 33,
          "quarter_3": 39,
          "quarter_4": 35,
          "over_time": null,
          "total": 137,
        },
        "away": {
          "quarter_1": 31,
          "quarter_2": 31,
          "quarter_3": 27,
          "quarter_4": 39,
          "over_time": null,
          "total": 128,
        },
      },
    }, {
      "id": 414753,
      "date": "2025-03-04T01:30:00+00:00",
      "time": "01:30",
      "timestamp": 1741051800,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "American Airlines Center",
      "status": { "long": "Game Finished", "short": "FT", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 138,
          "name": "Dallas Mavericks",
          "logo": "https://media.api-sports.io/basketball/teams/138.png",
        },
        "away": {
          "id": 157,
          "name": "Sacramento Kings",
          "logo": "https://media.api-sports.io/basketball/teams/157.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": 24,
          "quarter_2": 26,
          "quarter_3": 16,
          "quarter_4": 32,
          "over_time": null,
          "total": 98,
        },
        "away": {
          "quarter_1": 27,
          "quarter_2": 33,
          "quarter_3": 34,
          "quarter_4": 28,
          "over_time": null,
          "total": 122,
        },
      },
    }, {
      "id": 414754,
      "date": "2025-03-04T02:00:00+00:00",
      "time": "02:00",
      "timestamp": 1741053600,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "Delta Center",
      "status": { "long": "Game Finished", "short": "FT", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 160,
          "name": "Utah Jazz",
          "logo": "https://media.api-sports.io/basketball/teams/160.png",
        },
        "away": {
          "id": 140,
          "name": "Detroit Pistons",
          "logo": "https://media.api-sports.io/basketball/teams/140.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": 22,
          "quarter_2": 25,
          "quarter_3": 30,
          "quarter_4": 29,
          "over_time": null,
          "total": 106,
        },
        "away": {
          "quarter_1": 36,
          "quarter_2": 31,
          "quarter_3": 31,
          "quarter_4": 36,
          "over_time": null,
          "total": 134,
        },
      },
    }],
  },
}, {
  "league": "NBA",
  "data": {
    "get": "games",
    "parameters": {
      "date": "2025-03-05",
      "league": "12",
      "season": "2024-2025",
    },
    "errors": [],
    "results": 9,
    "response": [{
      "id": 414755,
      "date": "2025-03-05T00:00:00+00:00",
      "time": "00:00",
      "timestamp": 1741132800,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "Gainbridge Fieldhouse",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 143,
          "name": "Indiana Pacers",
          "logo": "https://media.api-sports.io/basketball/teams/143.png",
        },
        "away": {
          "id": 142,
          "name": "Houston Rockets",
          "logo": "https://media.api-sports.io/basketball/teams/142.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }, {
      "id": 414756,
      "date": "2025-03-05T00:00:00+00:00",
      "time": "00:00",
      "timestamp": 1741132800,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "Kia Center",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 153,
          "name": "Orlando Magic",
          "logo": "https://media.api-sports.io/basketball/teams/153.png",
        },
        "away": {
          "id": 159,
          "name": "Toronto Raptors",
          "logo": "https://media.api-sports.io/basketball/teams/159.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }, {
      "id": 414757,
      "date": "2025-03-05T00:30:00+00:00",
      "time": "00:30",
      "timestamp": 1741134600,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "State Farm Arena",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 132,
          "name": "Atlanta Hawks",
          "logo": "https://media.api-sports.io/basketball/teams/132.png",
        },
        "away": {
          "id": 148,
          "name": "Milwaukee Bucks",
          "logo": "https://media.api-sports.io/basketball/teams/148.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }, {
      "id": 414758,
      "date": "2025-03-05T00:30:00+00:00",
      "time": "00:30",
      "timestamp": 1741134600,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "Madison Square Garden",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 151,
          "name": "New York Knicks",
          "logo": "https://media.api-sports.io/basketball/teams/151.png",
        },
        "away": {
          "id": 141,
          "name": "Golden State Warriors",
          "logo": "https://media.api-sports.io/basketball/teams/141.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }, {
      "id": 414759,
      "date": "2025-03-05T01:00:00+00:00",
      "time": "01:00",
      "timestamp": 1741136400,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "United Center",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 136,
          "name": "Chicago Bulls",
          "logo": "https://media.api-sports.io/basketball/teams/136.png",
        },
        "away": {
          "id": 137,
          "name": "Cleveland Cavaliers",
          "logo": "https://media.api-sports.io/basketball/teams/137.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }, {
      "id": 414760,
      "date": "2025-03-05T01:00:00+00:00",
      "time": "01:00",
      "timestamp": 1741136400,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "Target Center",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 149,
          "name": "Minnesota Timberwolves",
          "logo": "https://media.api-sports.io/basketball/teams/149.png",
        },
        "away": {
          "id": 154,
          "name": "Philadelphia 76ers",
          "logo": "https://media.api-sports.io/basketball/teams/154.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }, {
      "id": 414761,
      "date": "2025-03-05T01:30:00+00:00",
      "time": "01:30",
      "timestamp": 1741138200,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "Frost Bank Center",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 158,
          "name": "San Antonio Spurs",
          "logo": "https://media.api-sports.io/basketball/teams/158.png",
        },
        "away": {
          "id": 134,
          "name": "Brooklyn Nets",
          "logo": "https://media.api-sports.io/basketball/teams/134.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }, {
      "id": 414762,
      "date": "2025-03-05T03:00:00+00:00",
      "time": "03:00",
      "timestamp": 1741143600,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "Footprint Center",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 155,
          "name": "Phoenix Suns",
          "logo": "https://media.api-sports.io/basketball/teams/155.png",
        },
        "away": {
          "id": 144,
          "name": "Los Angeles Clippers",
          "logo": "https://media.api-sports.io/basketball/teams/144.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }, {
      "id": 414763,
      "date": "2025-03-05T03:30:00+00:00",
      "time": "03:30",
      "timestamp": 1741145400,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "Crypto.com Arena",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 145,
          "name": "Los Angeles Lakers",
          "logo": "https://media.api-sports.io/basketball/teams/145.png",
        },
        "away": {
          "id": 150,
          "name": "New Orleans Pelicans",
          "logo": "https://media.api-sports.io/basketball/teams/150.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }],
  },
}, {
  "league": "NBA",
  "data": {
    "get": "games",
    "parameters": {
      "date": "2025-03-06",
      "league": "12",
      "season": "2024-2025",
    },
    "errors": [],
    "results": 8,
    "response": [{
      "id": 414764,
      "date": "2025-03-06T00:00:00+00:00",
      "time": "00:00",
      "timestamp": 1741219200,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "TD Garden",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 133,
          "name": "Boston Celtics",
          "logo": "https://media.api-sports.io/basketball/teams/133.png",
        },
        "away": {
          "id": 156,
          "name": "Portland Trail Blazers",
          "logo": "https://media.api-sports.io/basketball/teams/156.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }, {
      "id": 414765,
      "date": "2025-03-06T00:00:00+00:00",
      "time": "00:00",
      "timestamp": 1741219200,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "Spectrum Center",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 135,
          "name": "Charlotte Hornets",
          "logo": "https://media.api-sports.io/basketball/teams/135.png",
        },
        "away": {
          "id": 149,
          "name": "Minnesota Timberwolves",
          "logo": "https://media.api-sports.io/basketball/teams/149.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }, {
      "id": 414766,
      "date": "2025-03-06T00:00:00+00:00",
      "time": "00:00",
      "timestamp": 1741219200,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "Rocket Mortgage FieldHouse",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 137,
          "name": "Cleveland Cavaliers",
          "logo": "https://media.api-sports.io/basketball/teams/137.png",
        },
        "away": {
          "id": 147,
          "name": "Miami Heat",
          "logo": "https://media.api-sports.io/basketball/teams/147.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }, {
      "id": 414767,
      "date": "2025-03-06T00:00:00+00:00",
      "time": "00:00",
      "timestamp": 1741219200,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "Capital One Arena",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 161,
          "name": "Washington Wizards",
          "logo": "https://media.api-sports.io/basketball/teams/161.png",
        },
        "away": {
          "id": 160,
          "name": "Utah Jazz",
          "logo": "https://media.api-sports.io/basketball/teams/160.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }, {
      "id": 414770,
      "date": "2025-03-06T01:00:00+00:00",
      "time": "01:00",
      "timestamp": 1741222800,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "Fiserv Forum",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 148,
          "name": "Milwaukee Bucks",
          "logo": "https://media.api-sports.io/basketball/teams/148.png",
        },
        "away": {
          "id": 138,
          "name": "Dallas Mavericks",
          "logo": "https://media.api-sports.io/basketball/teams/138.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }, {
      "id": 414769,
      "date": "2025-03-06T02:00:00+00:00",
      "time": "02:00",
      "timestamp": 1741226400,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "Ball Arena",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 139,
          "name": "Denver Nuggets",
          "logo": "https://media.api-sports.io/basketball/teams/139.png",
        },
        "away": {
          "id": 157,
          "name": "Sacramento Kings",
          "logo": "https://media.api-sports.io/basketball/teams/157.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }, {
      "id": 414768,
      "date": "2025-03-06T02:30:00+00:00",
      "time": "02:30",
      "timestamp": 1741228200,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "FedExForum",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 146,
          "name": "Memphis Grizzlies",
          "logo": "https://media.api-sports.io/basketball/teams/146.png",
        },
        "away": {
          "id": 152,
          "name": "Oklahoma City Thunder",
          "logo": "https://media.api-sports.io/basketball/teams/152.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }, {
      "id": 414771,
      "date": "2025-03-06T03:30:00+00:00",
      "time": "03:30",
      "timestamp": 1741231800,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "Crypto.com Arena",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 144,
          "name": "Los Angeles Clippers",
          "logo": "https://media.api-sports.io/basketball/teams/144.png",
        },
        "away": {
          "id": 140,
          "name": "Detroit Pistons",
          "logo": "https://media.api-sports.io/basketball/teams/140.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }],
  },
}, {
  "league": "NBA",
  "data": {
    "get": "games",
    "parameters": {
      "date": "2025-03-07",
      "league": "12",
      "season": "2024-2025",
    },
    "errors": [],
    "results": 6,
    "response": [{
      "id": 414817,
      "date": "2025-03-07T00:00:00+00:00",
      "time": "00:00",
      "timestamp": 1741305600,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "Kia Center",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 153,
          "name": "Orlando Magic",
          "logo": "https://media.api-sports.io/basketball/teams/153.png",
        },
        "away": {
          "id": 136,
          "name": "Chicago Bulls",
          "logo": "https://media.api-sports.io/basketball/teams/136.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }, {
      "id": 414772,
      "date": "2025-03-07T00:30:00+00:00",
      "time": "00:30",
      "timestamp": 1741307400,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "Barclays Center",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 134,
          "name": "Brooklyn Nets",
          "logo": "https://media.api-sports.io/basketball/teams/134.png",
        },
        "away": {
          "id": 141,
          "name": "Golden State Warriors",
          "logo": "https://media.api-sports.io/basketball/teams/141.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }, {
      "id": 414773,
      "date": "2025-03-07T00:30:00+00:00",
      "time": "00:30",
      "timestamp": 1741307400,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "TD Garden",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 133,
          "name": "Boston Celtics",
          "logo": "https://media.api-sports.io/basketball/teams/133.png",
        },
        "away": {
          "id": 154,
          "name": "Philadelphia 76ers",
          "logo": "https://media.api-sports.io/basketball/teams/154.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }, {
      "id": 414774,
      "date": "2025-03-07T00:30:00+00:00",
      "time": "00:30",
      "timestamp": 1741307400,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "State Farm Arena",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 132,
          "name": "Atlanta Hawks",
          "logo": "https://media.api-sports.io/basketball/teams/132.png",
        },
        "away": {
          "id": 143,
          "name": "Indiana Pacers",
          "logo": "https://media.api-sports.io/basketball/teams/143.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }, {
      "id": 414775,
      "date": "2025-03-07T01:00:00+00:00",
      "time": "01:00",
      "timestamp": 1741309200,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "Smoothie King Center",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 150,
          "name": "New Orleans Pelicans",
          "logo": "https://media.api-sports.io/basketball/teams/150.png",
        },
        "away": {
          "id": 142,
          "name": "Houston Rockets",
          "logo": "https://media.api-sports.io/basketball/teams/142.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }, {
      "id": 414776,
      "date": "2025-03-07T03:00:00+00:00",
      "time": "03:00",
      "timestamp": 1741316400,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "Crypto.com Arena",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 145,
          "name": "Los Angeles Lakers",
          "logo": "https://media.api-sports.io/basketball/teams/145.png",
        },
        "away": {
          "id": 151,
          "name": "New York Knicks",
          "logo": "https://media.api-sports.io/basketball/teams/151.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }],
  },
}, {
  "league": "NBA",
  "data": {
    "get": "games",
    "parameters": {
      "date": "2025-03-08",
      "league": "12",
      "season": "2024-2025",
    },
    "errors": [],
    "results": 9,
    "response": [{
      "id": 414777,
      "date": "2025-03-08T00:00:00+00:00",
      "time": "00:00",
      "timestamp": 1741392000,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "Spectrum Center",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 135,
          "name": "Charlotte Hornets",
          "logo": "https://media.api-sports.io/basketball/teams/135.png",
        },
        "away": {
          "id": 137,
          "name": "Cleveland Cavaliers",
          "logo": "https://media.api-sports.io/basketball/teams/137.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }, {
      "id": 414778,
      "date": "2025-03-08T00:30:00+00:00",
      "time": "00:30",
      "timestamp": 1741393800,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "American Airlines Center",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 138,
          "name": "Dallas Mavericks",
          "logo": "https://media.api-sports.io/basketball/teams/138.png",
        },
        "away": {
          "id": 146,
          "name": "Memphis Grizzlies",
          "logo": "https://media.api-sports.io/basketball/teams/146.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }, {
      "id": 414779,
      "date": "2025-03-08T00:30:00+00:00",
      "time": "00:30",
      "timestamp": 1741393800,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "Scotiabank Arena",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 159,
          "name": "Toronto Raptors",
          "logo": "https://media.api-sports.io/basketball/teams/159.png",
        },
        "away": {
          "id": 160,
          "name": "Utah Jazz",
          "logo": "https://media.api-sports.io/basketball/teams/160.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }, {
      "id": 414780,
      "date": "2025-03-08T01:00:00+00:00",
      "time": "01:00",
      "timestamp": 1741395600,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "Kaseya Center",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 147,
          "name": "Miami Heat",
          "logo": "https://media.api-sports.io/basketball/teams/147.png",
        },
        "away": {
          "id": 149,
          "name": "Minnesota Timberwolves",
          "logo": "https://media.api-sports.io/basketball/teams/149.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }, {
      "id": 414781,
      "date": "2025-03-08T01:00:00+00:00",
      "time": "01:00",
      "timestamp": 1741395600,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "Paycom Center",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 152,
          "name": "Oklahoma City Thunder",
          "logo": "https://media.api-sports.io/basketball/teams/152.png",
        },
        "away": {
          "id": 156,
          "name": "Portland Trail Blazers",
          "logo": "https://media.api-sports.io/basketball/teams/156.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }, {
      "id": 414782,
      "date": "2025-03-08T03:00:00+00:00",
      "time": "03:00",
      "timestamp": 1741402800,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "Ball Arena",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 139,
          "name": "Denver Nuggets",
          "logo": "https://media.api-sports.io/basketball/teams/139.png",
        },
        "away": {
          "id": 155,
          "name": "Phoenix Suns",
          "logo": "https://media.api-sports.io/basketball/teams/155.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }, {
      "id": 414783,
      "date": "2025-03-08T03:00:00+00:00",
      "time": "03:00",
      "timestamp": 1741402800,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "Golden",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 157,
          "name": "Sacramento Kings",
          "logo": "https://media.api-sports.io/basketball/teams/157.png",
        },
        "away": {
          "id": 158,
          "name": "San Antonio Spurs",
          "logo": "https://media.api-sports.io/basketball/teams/158.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }, {
      "id": 414784,
      "date": "2025-03-08T03:30:00+00:00",
      "time": "03:30",
      "timestamp": 1741404600,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "Crypto.com Arena",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 144,
          "name": "Los Angeles Clippers",
          "logo": "https://media.api-sports.io/basketball/teams/144.png",
        },
        "away": {
          "id": 151,
          "name": "New York Knicks",
          "logo": "https://media.api-sports.io/basketball/teams/151.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }, {
      "id": 414785,
      "date": "2025-03-08T23:00:00+00:00",
      "time": "23:00",
      "timestamp": 1741474800,
      "timezone": "UTC",
      "stage": null,
      "week": null,
      "venue": "Spectrum Center",
      "status": { "long": "Not Started", "short": "NS", "timer": null },
      "league": {
        "id": 12,
        "name": "NBA",
        "type": "League",
        "season": "2024-2025",
        "logo": "https://media.api-sports.io/basketball/leagues/12.png",
      },
      "country": {
        "id": 5,
        "name": "USA",
        "code": "US",
        "flag": "https://media.api-sports.io/flags/us.svg",
      },
      "teams": {
        "home": {
          "id": 135,
          "name": "Charlotte Hornets",
          "logo": "https://media.api-sports.io/basketball/teams/135.png",
        },
        "away": {
          "id": 134,
          "name": "Brooklyn Nets",
          "logo": "https://media.api-sports.io/basketball/teams/134.png",
        },
      },
      "scores": {
        "home": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
        "away": {
          "quarter_1": null,
          "quarter_2": null,
          "quarter_3": null,
          "quarter_4": null,
          "over_time": null,
          "total": null,
        },
      },
    }],
  },
}];
